### ISSUE TITLE
Statische informatie

### ISSUE THREAD

**Issue by WesleySchorel** [iBadr49/connect-your-tribe-profile-visitekaartje#1]
https://github.com/iBadr49/connect-your-tribe-profile-card/blob/a2e65b91831bd820bd0dc953b379f0e20f20ed16/views/index.ejs#L13-L14

Deze regels lijken informatie uit je Bio. In de WhoIs.fdnd.nl Je zou deze informatie kunnen ophalen uit de Rest API.

**Comment by iBadr49** [comment]
Yes nu haal ik de bio info uit de api
