### ISSUE TITLE
<br>?

### ISSUE THREAD

**Issue by KoopReynders** [iBadr49/connect-your-tribe-profile-visitekaartje#10]
Opmaak (CSS) en structuur (HTML) zoveel mogelijk van elkaar scheiden. Je kan beter in CSS een margin zetten dan een `<br>` gebruiken. 

https://github.com/iBadr49/connect-your-tribe-profile-card/blob/95b5a0378d4372b8fbef8fc6c754936886953acb/views/index.ejs#L9

**Comment by iBadr49** [comment]
Yes, dat heb ik nu gedaan.
