### ISSUE TITLE
Statische informatie 

### ISSUE THREAD

**Issue by SanHont** [iBadr49/connect-your-tribe-profile-visitekaartje#2]
Deze informatie komt niet uit de API, dat is wel de bedoeling voor deze opdracht.

https://github.com/iBadr49/connect-your-tribe-profile-card/blob/a2e65b91831bd820bd0dc953b379f0e20f20ed16/views/contact.ejs#L8-L11

https://github.com/iBadr49/connect-your-tribe-profile-card/blob/a2e65b91831bd820bd0dc953b379f0e20f20ed16/views/index.ejs#L13-L14

**Comment by iBadr49** [comment]
Bro dat weet ik!
