### ISSUE TITLE
Deze code is overbodig

### ISSUE THREAD

**Issue by WesleySchorel** [iBadr49/connect-your-tribe-profile-visitekaartje#3]
https://github.com/iBadr49/connect-your-tribe-profile-card/blob/a2e65b91831bd820bd0dc953b379f0e20f20ed16/views/index.ejs#L3-L6

Nu je een mooi werkend visite kaartje hebt, kun je de eerste paar test lines weghalen.

**Comment by iBadr49** [comment]
Yes dat heb ik nu weggehaald
