### ISSUE TITLE
Is je visitekaartje in het engels?

### ISSUE THREAD

**Issue by KoopReynders** [iBadr49/connect-your-tribe-profile-visitekaartje#9]
Als je visitekaartje in het Nederlands is moet je dat hier neerzetten.

https://github.com/iBadr49/connect-your-tribe-profile-card/blob/95b5a0378d4372b8fbef8fc6c754936886953acb/views/partials/head.ejs#L2

**Comment by iBadr49** [comment]
OOOH JA 🤔 !!! Heb ik nu geswitcht naar nl.
